default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  password: <%= ENV.fetch('REDIS_PASSWORD', nil).presence %>
  channel_prefix: <%= "homestars_#{Rails.env}_action_cable"  %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
