version: "3.9"
volumes:
  redis:
  postgres:
services:
  redis:
    image: redis:6.0.9-alpine3.12
    restart: always
    command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
    env_file:
      - .env
    volumes:
      - redis:/data/redis
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: homestars_code_challenge:latest
    volumes:
      - ./:/app/
    env_file:
      - .env
    command: ./docker/entrypoints/start_app.sh app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
